require "cfdi_processor/version"
require "cfdi_processor/i18n"
require "cfdi_processor/data_extractor_base"
require "cfdi_processor/stamped_extractor"
require "cfdi_processor/document_type_detector"
require "cfdi_processor/retenciones_extractor"